ml4ai/tomcat

- .travis.yml
This PR sets up deployment to GitHub Pages (https://ml4ai.github.io/tomcat/). So far, it's basically Doxygen API docs, nothing too flashy. We can make it look nicer iteratively.
> GitHub Pages setup

- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Goal/KillEntityGoal.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/TutorialMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/GuiBackground.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/InstructionsScreen.java
GuiBackground.java and InstructionScreen.java were made to add a background to instructions for readability.
KillEntityGoal.java and TutorialMission.java were made to add a task called "battle one monster".
> add background & battle one monster

- docs/prebuilt_world_loading.md
This adds some instructions for loading a pre-built world
> Prebuilt world loading instructions

- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Goal/KillEntityGoal.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/GuiBackground.java
I just corrected comments and removed shadow under the instructions. At first, I want to update it together with inserting an image, but there is still the bug when importing image.
> correct comments & remove shadow under the instructions

- .gitignore
- docs/installation.md
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/SARMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/TutorialMission.java
- src/TomcatMission.cpp
This PR:
* replaces the hard-coded path in `src/TomcatMission.cpp` with an environment variable, and updates the documentation appropriately
* implements minor edits to the documentation including streamlining the install process a bit (i.e. making it more copy-paste friendly)
* Changes 'Press OK' to 'Click OK' in the mission dialogues.
> Documentation and usability updates

- docs/index.rst
- docs/installation.md
This PR:
* fixes a path to Mission.java in installation.md
* Adds a link to the PDF of the slideshow that was presented at the site visit on 9/25.
> Documentation updates

- KB-notes.txt
- tools/download_tomcat_data.sh
- tools/install.sh
- tools/install_dependencies.sh
Some tweaks to the install scripts to catch errors that could occur.
> Added some checks to the install scripts.

- external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/Server/MalmoModServer.java
- external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Client/ClientMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/MissionHandler.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/MissionListener.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/QuitProducer.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/SARMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/TutorialMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/RichContentScreen.java
Now all the tomcat missions run the clean-up steps executed by the Malmo missions which allow the tracked data (video, audio, chat etc.) to be saved after the mission ends.
> Mission ending cleanup

- CMakeLists.txt
This PR fixes an issue arising from a recent update to macOS Catalina.
> macOS Catalina update fix

- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/SARMission.java
This PR fixes a building randomization bug where buildings were accidentally not being selected at random.
> fixing randomness bug

- tools/install_dependencies.sh
This PR updates the dependency installation on Ubuntu to use the required Java version.
> Ubuntu Java Dependency

- .github/workflows/macOS.yml
- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instruction_crafting.json
- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instructions_arena.json
- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instructions_entities.json
- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instructions_pits.json
- tools/activate_minecraft_window.scpt
- tools/install_dependencies.sh
- tools/run_session.sh
- tools/wrap_launch_minecraft.sh
This PR implements a number of bug fixes and improvements, most importantly getting ffmpeg recording to work again.
> Bugfixes and improvements

- external/malmo/Malmo/src/VideoFrameWriter.h
- external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/ASISTBlocks/BlockAsistIron.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Goal/ActivateButtonGoal.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Goal/OpenDoorGoal.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/SARMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/TutorialMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/DiscreteEventsHelper.java
- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instructions_entities.json
- Removing crafting phase temporarily;
- Changing approach entities strategy (buttons have to be hit by the player now);
- Placing entities in their positions dynamically;
- Preventing the player to die (the character is respawned in the initial position with full health whenever it dies).
> Improvements in the Tutorial Mission

- tools/install
- tools/install_dependencies
This PR implements a fix for macOS installation testing on Github Actions.
> Homebrew fix

- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Client/USARSinglePlayerClientMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/MissionSelfReport.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/USARSinglePlayerMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/ZombieMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportContent.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportFileHandler.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportQuestion.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportResponses.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportScreen.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/SelfReportSingleResponse.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/Converter.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/OutputDataHandler.java
- external/malmo/Minecraft/src/main/resources/assets/malmomod/self_report/self_report1.json
- tools/run_session
- Added more 2 button choices to the last self-report question
- Formatted the output of the responses to comply with the pattern we designed
- Fixed error that happened when no self-report folder existed
> Adjusting self-report output data formatting

- external/malmo/Minecraft/src/main/resources/assets/malmomod/rich_content/tutorial_instructions_entities.json
Add instuctions to push the button: add two images to the instruction.
Specific goals: not work.
> Add instructions to push the button

- external/malmo/Minecraft/run/options.txt
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/DogBarkEvent.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/ForgeEventHandler.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/USARSinglePlayerMission.java
This PR implements additional support for the USAR Singleplayer mission.
- The time limit has been disabled when running the USAR Singleplayer mission.
- An event class has been created for Dog bark events. Example:
```json
{
"number_of_barks": 1,
"event_type": "edu.arizona.tomcat.Events.DogBarkEvent",
"timestamp": "2020-05-04T18:50:41:863Z"
}
Additionally, fancier graphics are now enabled by default.
> Additional support for USAR Singleplayer mission

- tools/install_soartex_fanver
This PR adds a helper script to install the textures from the Soartex Fanver texture pack.
> Adding helper script to install Soartex Fanver texture pack

- tools/generate_session_metadata
This PR implements hashing of the player ID field in the `generate_session_metadata` script for greater anonymity.
> Implemented SHA256 hashing of player ID in metadata file.

- src/cpp/pro_gen/AABB.cpp
- src/cpp/pro_gen/AABB.h
- src/cpp/pro_gen/Block.cpp
- src/cpp/pro_gen/Block.h
- src/cpp/pro_gen/Pit.h
- src/cpp/pro_gen/Pos.cpp
- src/cpp/pro_gen/Pos.h
- src/cpp/pro_gen/ProceduralGenerator.cpp
- src/cpp/pro_gen/ProceduralGenerator.h
- src/cpp/pro_gen/World.cpp
- src/cpp/pro_gen/World.h
- src/cpp/pro_gen/gridworld_generator.cpp
- src/cpp/pro_gen/zombieworld_generator.cpp
* Documentation Refactored
* Documentation moved to header files.
* Header files use names for parameters to match documentation for consistency.
* Added some missing documentation and fixed typos. Ordering in header and CPP files now match.
* Using C++11 standard pseudo-random generator instead of boost library equivalent (Still using Mersenne Twister).  
* Added program option to specify JSON and TSV file path in `gridworld_generator`.
* The `ProceduralGenerator` class is now empty, and `getRandomVictims()` has been moved to `gridworld_generator` because it is relatively specific.
> Procedural Generation General Refactoring

- src/python/model/hackathon/evaluation.py
- src/python/model/hackathon/evidence_extraction.py
- src/python/model/hackathon/inference.py
- src/python/model/hackathon/model_representation.py
- src/python/model/hackathon/ta3_data_adapter.py
- src/python/model/requirements.txt
Predicting future nodes with arbitrary horizon in the python version of the model.
> Extended prediction

- docs/spec.yml
- external/malmo/Minecraft/run/devmode.json
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/CommandExecuted.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/ForgeEventHandler.java
Fully implemented command event handling, namely including a devmode json file to whitelist commands outside of developer mode or enable developer mode if all commands are permissible. Publishes command name, argument, and issuer to event bus.
> Command developer mode

- Dockerfile
- tools/install
Dockerfile to build openface(and tomcat). 
tools/install assumed CI variable to be always set for linux which does not hold true for docker. A potential bug waiting to be addressed.
> Openface docker

- external/OpenFace/lib/LandmarkDetector/include/LandmarkDetectorFunc.h
- external/OpenFace/lib/LandmarkDetector/src/LandmarkDetectorFunc.cpp
This PR adds some extra comments to the OpenFace code.
> Adding extra comments to OpenFace code

- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/ProceduralGenMission.java
- external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/WorldBuilder.java
* Added a flag in Java to toggle saving the block map and entity UUID set after use
* Shortened code for giving entities equipment and added debug messages
> Save flag for block map and UUID set

- tools/boris_helper
This PR adds a script to automate installing the BORIS annotation tool on macOS.
> Adding boris_helper script

- tools/asist/README.md
- tools/asist/combine_annotations
This PR adds a script to combine annotations of the Incident Commander Inquiries in the ASIST Fall 2020 experiment done using the BORIS Tool.
> Annotation combination script

- docs/team.md
This PR updates team.md with an updated list of members.
> Updating team.md

- docs/software.rst
This PR fixes a couple of links in the website and adds tomcat-speechAnalyzer to the list of software components.
> Updating list of ToMCAT software components

- docs/preregistrations/asist_study_3/sections/entrainment_detection.tex
Added text to entrainment section. it goes over 1 page.
> first_draft

- exe/cpp_agent_template/Agent.cpp
> Changing heartbeat period to 10 seconds

- docs/developer/metadata_files.rst
This PR adds instructions for replaying messages using the `elkless_replayer`.
> Adding replay instructions

- human_experiments/scripts/end_experiment
- human_experiments/scripts/run_experiment
- human_experiments/scripts/start_lab_recorder
- human_experiments/scripts/stop_lab_recorder
- human_experiments/scripts/stop_recording.py
I made some changes and added a step to "tomcat/human_experiments/scripts/run_experiment".
I finished developing the scripting in "tomcat/human_experiments/scripts/start_lab_recorder".
I created a script "tomcat/human_experiments/scripts/stop_lab_recorder" and a python script "tomcat/human_experiments/scripts/stop_recording.py".
All have been tested in last dry run and worked correctly.
> LabRecorder start/stop scripts

- human_experiments/scripts/end_experiment
- human_experiments/scripts/run_experiment
> Kill audio streamer

- human_experiments/scripts/end_experiment
- human_experiments/scripts/run_experiment
> No mumble no tom

- human_experiments/scripts/retrieve_minecraft_data
> Using @timestamp instead of msg.timestamp to sort the documents.

- human_experiments/lab_software/tomcat-baseline-tasks/run_baseline_tasks_data_validation.py
- human_experiments/scripts/run_minecraft_metadata_validation.py
1. Checks if the metadata file exists or not.
2. Displays subject ID.
3. Mission start and stop.
4. Duration of the mission.
Execution:` python3 run_minecraft_metadata_validation.py --p \<path to Minecraft metadata data directory>`
1. Check if folders ['finger_tapping', 'rest_state', 'affective', 'ping_pong'] exist or not.
2. Counts number of csv files under each of folders.
3. Checks if the CSV files are empty or not.
4. Displays start- and stop- time of the particular task.
5. Calculates how long a task took to complete and checks if its within the range mentioned in task config file.
6. Reads Subject ID from the CSV file and compares it to subject ID passed as argument.
Execution: `python3 run_baseline_tasks_data_validation.py --p \<path to baseline task data directory> --s …
> Post exp data validation

- human_experiments/scripts/sync_tom_and_cat
- human_experiments/scripts/sync_tom_and_cat_2
This next iteration features tweaks to rsync args (no -o) and documentation updates for our evolving use cases.
> Sync script dev

- human_experiments/scripts/play_instructive_video
- human_experiments/scripts/run_experiment
> Video order

- human_experiments/scripts/sync_tom_and_cat
> Deleted some spurious lines from broken merge. Patched a comment.

- human_experiments/lab_software/tomcat-physio-viz/EEG_plot.py
- human_experiments/lab_software/tomcat-physio-viz/SendData.py
- human_experiments/lab_software/tomcat-physio-viz/fNIRS_plot.py
Now physio plots gets chunks of samples accumulated while plotting the previous sample and only plots the last sample of each chunk skipping all the samples it did not get to in time.
Did some code cleanup and rearrangement.
> Fixed the lagging behind of physio plots

- human_experiments/scripts/check_disk_space
- human_experiments/scripts/extract_testbed_logs
- human_experiments/scripts/run_experiment
Extract logs, move them to the experiment folder and untar in the end of an experiment.
> Testbed logs

- human_experiments/scripts/inventory_script/inventory_script.py
- human_experiments/scripts/inventory_script/utils/__init__.py
- human_experiments/scripts/inventory_script/utils/run_baseline_tasks_data_validation.py
- human_experiments/scripts/inventory_script/utils/run_minecraft_metadata_validation.py
- human_experiments/scripts/inventory_script/utils/run_pupil_capture_validation.py
- human_experiments/scripts/inventory_script/utils/run_xdf_check.py
The inventory script checks the following directories/files:
1. Baseline task data
2. Minecraft metadata
3. xdf files
4. pupil capture (eye0.mp4, eye1.mp4 and world.mp4)
5. Audio (.wav) files for each subject
6. Checks asist_logs_*.tar file
7. Checks for vocalic features 
Output of the inventory script:
[script.log](https://github.com/ml4ai/tomcat/files/9893023/script.log)
> Inventory  script

- human_experiments/lab_software/xdf_to_csv_conversion/XDF_to_csv.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/NIRS_filtering.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/__init__.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/baseline_tasks_timestamps.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/convert_datetime_timezone.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/create_time_distribution.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/create_write_csv_file.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/minecraft_timestamps.py
- human_experiments/lab_software/xdf_to_csv_conversion/utils/xdf_timestamps.py
Added 2 more functions:
1. Calculates coefficient of variance from Rest State block of the experiment and labels it as good or bad channel based on the value. 
2. Filters the signal using butter-worth band pass filter with high pass set to 0.2Hz, lowpass set to 0.01Hz and filter order set to 3.
> Filter nirs

- rust/tomcat/src/config.yml
- rust/tomcat/src/main.rs
- rust/tomcat/src/messages/chat.rs
Extractions are now created from Dialog Agent REST API input
These are output to the screen for now.
> Rust joseph

- human_experiments/lab_software/tomcat-images-timestamp/.gitignore
- human_experiments/lab_software/tomcat-images-timestamp/CMakeLists.txt
- human_experiments/lab_software/tomcat-images-timestamp/README.md
- human_experiments/lab_software/tomcat-images-timestamp/fileChecker.cpp
- human_experiments/lab_software/tomcat-images-timestamp/publish/CMakeLists.txt
- human_experiments/lab_software/tomcat-images-timestamp/publish/publish.cpp
- human_experiments/lab_software/tomcat-images-timestamp/publish/publish.h
- human_experiments/lab_software/tomcat-images-timestamp/scripts/timestampRename.py
File timestamp program for recording when images are created and rename the images as post processing.
> Add program for timestamping images

- human_experiments/scripts/rename_image_timestamp
- human_experiments/scripts/run_experiment
- human_experiments/scripts/start_ffmpeg
- human_experiments/scripts/start_fnirs_eeg_visualizer
- human_experiments/scripts/start_lab_recorder
- human_experiments/scripts/stop_data_streaming_processes
Sorry for adding 2 features into the same pull request. The EEG things are the changes probably by @CalebUAz or @rchamplin. I am unable to figure out who wrote them, and I did not want to discard these changes, so I include them anyway.
The timestamp program is supposed to:
- Launch the timestamp monitor program in the background with tmux.
- Once the image streaming processes end, also close timestamp monitor program.
- Rename images as their timestamps.
> Launch image timestamp monitor and rename programs from Uberscript, and visualize EEG

- human_experiments/config/LabRecorder_config/LabRecorder_Lion_22345.cfg
- human_experiments/lab_software/tomcat-physio-viz/EEG_plot.py
- human_experiments/scripts/start_lab_recorder_test_open_1_inst
- Change Lion config file for labrecorder to use Cheetah's AMP.
- Add start lab recorder test script for troubleshooting and testing.
- Add Caleb's EEG plot fix.
> Change Lion Config, add lab recorder test script, add EEG plot fix

- human_experiments/lab_software/tomcat-physio-viz/EEG_plot.py
Update: Since 11/22, the lab has been using 23 channels instead of 33 channels, so the EEG_plot has been update to plot only those 23 channels rather than all 33.
> update EEG channel list

- human_experiments/lab_software/tomcat-baseline-tasks/tasks/affective_task/client.py
- human_experiments/lab_software/tomcat-baseline-tasks/tasks/affective_task/server.py
- Log events in the affective task, such as when blank screens are shown, when images are shown, etc.
> log events for affective task

- human_experiments/lab_software/tomcat-physio-viz/EEG_plot.py
- human_experiments/lab_software/tomcat-physio-viz/fNIRS_plot.py
- Somebody changed the actichamp config file which caused the EEG_plot.py to crash due to an overflow issue. 
- But now the script adopts the changed actichamp config file.
> EEG overflow bug fix

- data_products/scripts/backup_tom_and_cat
- data_products/scripts/backup_tom_and_cat_2
- data_products/scripts/cleanup_rsync_backups
- data_products/scripts/pull_tomcat_data
- data_products/scripts/pull_tomcat_data_2
Pulling data scripts are now somewhat stable on i03, and development can continue on the main branch.
> Data processing on i03

- human_experiments/datasette_interface/build_base_tables.py
- human_experiments/datasette_interface/build_database_from_scratch.sh
- human_experiments/datasette_interface/common/__init__.py
- human_experiments/datasette_interface/common/extract_signal_xdf.py
- human_experiments/datasette_interface/launch_dev.sh
- human_experiments/datasette_interface/metadata.yml
- human_experiments/datasette_interface/process_affective_task_data.py
- human_experiments/datasette_interface/process_eeg_data.py
- human_experiments/datasette_interface/process_fingertapping_task_data.py
- human_experiments/datasette_interface/process_fnirs_data.py
- human_experiments/datasette_interface/process_ping_pong_competitive_data.py
- human_experiments/datasette_interface/process_ping_pong_cooperative_data.py
- human_experiments/datasette_interface/process_rest_state_task_data.py
- human_experiments/datasette_interface/process_testbed_messages.py
- human_experiments/datasette_interface/requirements.txt
- human_experiments/datasette_interface/utils.py
Import EEG signals from XDF file, label them, and export the data to sqlite3 database
> EEG data processing

- docs/data_products/data_products.tex
- docs/data_products/references.bib
- docs/data_products/sections/derived_data.tex
- docs/data_products/sections/derived_data_description.tex
Update the derived data section to reflect the latest state of the derived data.
> Derive data update

- human_experiments/tomcat_training/video_player.html
Web video player for ToMCAT training video. (video_player.html)
> training videos player

- human_experiments/datasette_interface/bin/clear_database.py
- human_experiments/datasette_interface/datasette_interface/common/config.py
- human_experiments/datasette_interface/datasette_interface/database/config.py
- human_experiments/datasette_interface/datasette_interface/database/entity/signal/fnirs.py
- human_experiments/datasette_interface/datasette_interface/raw/process_base_tables.py
- human_experiments/datasette_interface/requirements.txt
In the process of testing the postgres db construction pipeline, I implemented a few fixes and added a couple of features.
> Fixes arising from testing postgres db construction
