ml4ai/tomcat

.travis.yml, external/OpenFace/lib/local/FaceAnalyser/include/FaceAnalyser.h, external/OpenFace/lib/local/FaceAnalyser/include/FaceAnalyserParameters.h, external/OpenFace/lib/local/LandmarkDetector/include/CNN_utils.h, external/OpenFace/lib/local/LandmarkDetector/include/FaceDetectorMTCNN.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkCoreIncludes.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkDetectionValidator.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkDetectorFunc.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkDetectorModel.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkDetectorParameters.h, external/OpenFace/lib/local/LandmarkDetector/include/LandmarkDetectorUtils.h, external/OpenFace/lib/local/LandmarkDetector/include/PDM.h, external/OpenFace/lib/local/LandmarkDetector/include/Patch_experts.h, external/OpenFace/lib/local/LandmarkDetector/src/LandmarkDetectorParameters.cpp, external/OpenFace/lib/local/Utilities/include/VisualizationUtils.h, external/OpenFace/lib/local/Utilities/include/Visualizer.h, src/WebcamSensor.h
This PR:
* Fixes the loading of the face landmark detector parameters in OpenFace, to now use the `TOMCAT` environment variable
* Cleans up and refactors the OpenFace source code a bit.
=> Fixed loading of face landmark detector parameters in OpenFace

external/malmo/Malmo/src/AgentHost.cpp, external/malmo/Malmo/src/MissionRecord.cpp, external/malmo/Malmo/src/MissionSpec.cpp, tools/install_dependencies.sh
This PR:
* Cleans up Malmo code a bit, adding `this->` to explicitly point out class membership, and also auto formatting using `clang-format`.
* Adds a script, `upload_to_vanga`, that can be used to upload tomcat data to vanga.sista.arizona.edu so that it can be downloaded by the public. See comments in the script for instructions on usage.
=> Malmo code cleanup and script added to upload to vanga

.travis.yml, CMakeLists.txt, src/CMakeLists.txt, src/Microphone.cpp, src/Microphone.h, src/runExperiment.cpp, tools/install.sh, tools/install_dependencies.sh
This PR moves the Homebrew package installations from being defined in `.travis.yml` to `tools/install.sh`, for better debugging (this way the Travis build runs with the same command as the end user build, which is good for debugging purposes.
=> Updating Travis config and installation scripts

CMakeLists.txt
This PR updates CMakeLists.txt to enforce the C++17 standard only on MacOS (so that warnings about multiple using directives are suppressed). On Ubuntu, this breaks compilation since the version of dlib obtained with apt-get doesn't comply with the standard.
=> Adding an if statement to only require C++17 with macOS

external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Messaging/TomcatMessaging.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Client/TutorialClientMission.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/TutorialMission.java
This PR implements some changes to the Tutorial Mission Views:
1) View change at the start of the tutorial mission is on the client side instead of the server (The server messages the client now). The server side logic was cleaned up a little and then abstracted into one function.
2) 3 seconds per view was very long, so the player now stays in each view mode for 1.5 seconds instead of 3. 
3) The Approach Pools Phase now starts at the 5th second instead of the 10th because the different views are now shown faster.
=> View modes client server separation

src/Mission.h
PR #51 accidentally removed the automatic timestamping of output data files. This PR adds them back.
=> Adding timestamps back after they were accidentally removed in PR #51

tools/download_OpenFace_models.sh, tools/download_tomcat_worlds.sh, tools/install.sh, tools/install_boost_from_source.sh, tools/install_cmake_from_source.sh, tools/install_dependencies.sh, tools/install_dlib_from_source.sh, tools/install_opencv_from_source.sh
This PR refactors the installations scripts for greater modularity and creating a Docker image based on Ubuntu Bionic.
New scripts: `tools/install_<cmake/boost/opencv/dlib>_from_source.sh`
The scripts also now specify a particular commit of Dlib to download and install, since the latest release of Dlib (19.19) does not work with OpenCV 4.2.0 and OpenCV 3.4.9.
Extracting files from .tgz and .zip files is now quieter.
=> Installation script refactoring

src/Mission.cpp
This PR limits the kind of interactions a player can have with their environment by setting the default game-mode to "Adventure" in Mission.cpp.
The player will not be able to break anything with hands or any tools (except specially tagged tools, but that is not included in this PR because the player isn't using tools to break anything in our missions yet.)
The player can still craft, pick up items, click buttons and levers and hit entities. This also means that given a weapon, the player can hit entities with it.
=> Constrain Player

tools/README.md, tools/install_dependencies.sh, tools/local-ports/openjdk8/Portfile
This PR adds the functionality to automatically install the required version of Java for MacPorts users. 
* A new directory, `tools/local-ports` has been created to address the cases for MacPorts users where a required dependency is not available in the upstream MacPorts tree.
* A `README.md` file has been added to the `tools` directory.
* The installation scripts have been updated appropriately.
=> Adding local Portfile for Java 1.8.0_232

external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoModClient.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/GUIScreenUndismissableOnEscapeKey.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/gui/MessageScreen.java
Issue with the mouse cursor was fixed. I am asking Minecraft to ungrab the mouse when a screen prompts. Now we don't need to use malmo mouse behaviour anymore and we can still have the cursor shown on the screen so that the player can press a button.
=> Fixing issue with the mouse

.gitignore, external/malmo/Malmo/src/AgentHost.cpp, external/malmo/Malmo/src/BmpFrameWriter.cpp, external/malmo/Malmo/src/BmpFrameWriter.h, external/malmo/Malmo/src/MissionRecord.h, external/malmo/Malmo/src/MissionRecordSpec.h, external/malmo/Malmo/src/PosixFrameWriter.cpp, external/malmo/Malmo/src/PosixFrameWriter.h, external/malmo/Malmo/src/StringServer.cpp, external/malmo/Malmo/src/TCPClient.cpp, external/malmo/Malmo/src/TimestampedVideoFrame.cpp, external/malmo/Malmo/src/TimestampedVideoFrame.h, external/malmo/Malmo/src/VideoFrameWriter.cpp, external/malmo/Malmo/src/VideoFrameWriter.h, external/malmo/Malmo/src/VideoServer.cpp, external/malmo/Malmo/src/VideoServer.h, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/Client/VideoHook.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlerInterfaces/IVideoProducer.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/VideoProducerImplementation.java, tools/check_minecraft.sh, tools/download_OpenFace_models.sh, tools/download_tomcat_worlds.sh, tools/get_minecraft_window_position_and_size.scpt, tools/install.sh, tools/install_boost_from_source.sh, tools/install_dlib_from_source.sh, tools/run_session.sh, tools/run_tutorial
ffmpeg integration, data collection streamlining, script refactoring
================================================
This PR implements ffmpeg integration to record video of the player's face using the built-in webcam, video of the Minecraft window, and audio of the player while they are playing the game. It also streamlines data collection a bit and implements some refactoring of the scripts.
FFmpeg integration
--------------------
The three aforementioned input streams are essential for the ToMCAT research effort. Video of the player's face will be analyzed for affect, video of the Minecraft window will be used to establish human observer baselines and maybe in the service of retrospective self-report, and the audio recording will be used as input to the natural language dialogue …
=> FFmpeg integration, data collection streamlining, script refactoring

tools/activate_minecraft_window.scpt, tools/get_minecraft_window_position_and_size.scpt, tools/run_session.sh
Since it turns out the experiments will be conducting with Minecraft running full screen, we don't really need to crop the ffmpeg recording area after all. This PR removes the code to find out the cropping bounds and replaces it with code to bring the Minecraft window to the foreground and make it full screen.
It also adds a flag to ffmpeg to make sure that the screen recording is not choppy when full screen, but stays at 30 fps.
=> Full screen ffmpeg recording

external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/ASISTBlocks/BlockAsistButton.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/ASISTBlocks/BlockAsistLever.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoModClient.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/DiscreteEventsHelper.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/TomcatForgeEventHandler.java, external/malmo/Minecraft/src/main/resources/assets/malmomod/blockstates/asist_button.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/blockstates/asist_lever.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_button.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_button_inventory.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_button_pressed.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_lever.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_lever_off.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/item/asist_button.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/item/asist_lever.json, tools/run_session.sh
This PR does a few small things:
1) Textures have been added for both the `Asist Button` and `Asist Lever`. They look like the Minecraft stone button and lever.
Fixes #69 
2) The output for discrete events is now appended to a file called `Discrete_Events.json` in the 
`Minecraft/run/saves/discrete_events` directory. There is only one file created each time because each event log holds time data.
Note: Technically, the methods that output the event log are called twice - once by the server and once by the client. I was unable to separate these calls, so each method is called twice in succession. The `DiscreteEventsHelper` uses a counter to disregard every other call, which results in each event log only being written once to the JSON file. 
This would need to be tested once the client and …
=> Discrete events 2+

CMakeLists.txt, docs/beginner_setup_instructions.md, docs/installation.md, tools/install.sh, tools/install_boost_from_source.sh, tools/install_dependencies.sh, tools/run_session.sh
- Scripts have been updated so that CMakeLists.txt requires an exact Java version (1.8), and if MacPorts has been used to install openjdk8, then the build will detect that version of Java even if there are other Java versions on the system.
- Added a couple more places where the return code is checked, scripts are more consistent about declaring and assigning separately (https://github.com/koalaman/shellcheck/wiki/SC2155)
- `rm` has been replaced by `/bin/rm` to avoid conflicts with aliases
- `CMakeLists.txt` enforces the C++17 standard.
- `docs/beginner_setup_instructions.md` now includes explanations of giving the terminal permission to control system events, webcam, and microphone.
- `docs/installation.md` updated to include instructions for how to quit the mission and exit the game.
- …
=> Improvements to installation and session running scripts.

external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java, tools/run_session.sh
This branch solves the following problems:
1. Observations were not being collected. Its was missing the flag --record_observations in the call to the runExperiment script inside the run_session script.
2. Self-reports are now being moved to the participant_data folder in the end of the mission.
=> Observations & Self-reports

external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/ASISTBlocks/BlockAsistIron.java, external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/ASISTBlocks/ModBlocks.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/DiscreteEventsHelper.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Utils/TomcatForgeEventHandler.java, external/malmo/Minecraft/src/main/resources/assets/malmomod/blockstates/asist_iron_block.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/lang/en_US.lang, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/block/asist_iron_block.json, external/malmo/Minecraft/src/main/resources/assets/malmomod/models/item/asist_iron_block.json
This PR implements two things:
1) A new block called `Asist Iron Block` has been created to replace the `Iron Block` being used in the Hit-Controlled Doors. These blocks write an output saying "Hit-Controlled Door Opened" when it is destroyed through a command (not by a player since the player never directly breaks it). 
2) The Attack Entity Event now uses a subclass of `Entity` called `EntityMob` when looking for target data, so it can measure the current enemy health each time the event is fired. This is reported as current health/max health. The same has been done for the player as well.
Outputs are written to the same `discrete_events.json` file.
=> Discrete events 3 - Hit-Control Door Open Event and Health Measurement

external/malmo/Malmo/src/VideoFrameWriter.h
This PR fixes a compilation error with GCC 7.5.0 on Ubuntu 18.04.
=> Adding #include <stack> to VideoFrameWriter.h

CMakeLists.txt, docs/installation.md, external/malmo/CMakeLists.txt
This PR increments the minimum version of Boost required to 1.69 to fix a compilation error on some macOS machines.
See also: https://github.com/boostorg/atomic/issues/15
=> Bumping minimum Boost version to 1.69

tools/run_session.sh
The run_session.sh script now checks the error logs for specific error messages, and exits if the test audio and video files cannot be created, and the error messages are not found in the log file. The complete error log is printed to screen if the log file does not contain one of the known errors.
=> Making ffmpeg testing more robust

tools/run_session.sh
Ubuntu and macOS seem to behave differently regarding complaining about unbound variables - in particular, `declare -x` doesn't seem to work on Ubuntu. Here is a more elegant workaround, suggested by @kobus-barnard .
=> A better way to deal with Ubuntu-macOS bash behavior discrepancy

src/Mission.cpp, tools/configure_session, tools/macos/test_system_audio_recording, tools/macos/test_webcam, tools/run_session, tools/run_tutorial
This PR implements
- Fixes to the scripts to make them work with MacBook Pros that have the framerate issue (where we need to specify a framerate of 30 for the webcam).
- Adds a slash to the tomcat directory in `src/Mission.cpp` - it caused an error on Savannah's computer.
- Removes the kind of scary framerate error message in the scripts - the script just handles the error now.
- Separate error logs are created for the microphone and webcam for the main mission (vs the tests).
- Tutorial mission outputs are redirected to `/dev/null` and the `--record_path` option has been removed from the `run_tutorial` script.
=> Miscellaneous fixes.

docs/developer/index.rst, docs/developer/minecraft_forge_events.md
This PR adds a lightly-curated list of discrete events that are available on the Minecraft Forge (v 1.11.2) event bus that could be useful for ToMCAT research activities. We can look over these and decide which ones we want to prioritize implementing subscriptions to. (Thanks to @Adi-UA for compiling the initial list).
=> Adding list of potentially useful Minecraft events

external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/BlockBreakEvent.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/BlockInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/DoorInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/EntityDeath.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/Event.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/ForgeEventHandler.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/IronDoorOpened.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/LeverFlip.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/MobAttacked.java
Additional events: Lever flip, door open, block break, left clicks
=============================================
This PR implements a few additional events: lever flips, door opening, block breaking, and left clicking - to support the USAR single player mission.
A new field, `block_material` has been added to the data structure, and the `event_type` field now reflects the fully-qualified name of the corresponding event class (to accurately capture hypernymy relations between event types).
Examples
----------
Event representing a block interaction (will be dispatched to different message bus topics depending on whether it was a left click or right click).
```json
{
"player_name": "tomcat",
"block_position": {
"x": -2183.0,
"y": 53.0,
"z": 177.0
},
"block_type": …
```
=> Additional events: Lever flip, door open, block break, left click

external/malmo/Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/BlockInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/ForgeEventHandler.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
This PR fixes an issue where duplicate events were being fired when players right-clicked blocks that were not meant to be interacted with via right clicks (i.e. unlike doors, levers, etc). An event would be fired for both the 'main' hand and the 'off' hand - we now restrict the event to fire only for the 'main' hand.
The ForgeEventHandler class is now being registered outside `MalmoMod.java` inside its constructor - it has been turned into a singleton class.
Additionally, `BlockInteraction` events now specify whether the interaction was a left or right click.
=> Fixing issue with duplicate RightClickBlock events, moving event handler registration outside MalmoMod.java

external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/BlockBreakEvent.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/BlockInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/DoorInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/EntityInteraction.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/Event.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/ForgeEventHandler.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/LeverFlip.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Events/MobAttacked.java, external/malmo/Minecraft/src/main/java/edu/arizona/tomcat/Mission/Mission.java
Adding EntityInteraction events, information about item held for block and entity interactions
===================================================================
This PR implements a new event type: EntityInteraction: when a player interacts with an entity, but the interaction is not an attack - e.g. putting the lead on the search-and-rescue assistant dog in the USAR Singleplayer mission. It also adds data about what item the player was holding for `BlockInteraction`,  `BlockBreak`, and `MobAttack` events, and autoformatting.
Examples
----------
```json
{
"player_name": "tomcat",
"target_type": "net.minecraft.entity.passive.EntityWolf",
"target_id": "cc463636-3d6e-453f-8810-bffeb2df1a80",
"target_position": {
"x": -2160.50634765625,
"y": 52.0,
"z": 179.57275390625
},
"target_velocity": { …
```
=> Added EntityInteraction events, data about item held in events

tools/configuration_helpers, tools/generate_session_metadata, tools/run_session
This PR adds a PLAYER_ID variable that can be set during internal data collection if a team member is having a friend/family member play the mission on their laptop.
Example usage:
PLAYER_ID="Wilbur Wildcat" MAIN_MISSION=2 ./tools/run_session
=> Adding PLAYER_ID variable

tools/extract_TA3_world
This PR implements a fix in `extract_TA3_world` for the situation where Ubuntu appends the `.gz` suffix to `.tgz` files downloaded from Google Drive.
=> Fix for Ubuntu adding .gz suffix to .tgz files downloaded from Google Drive

tools/run_session
This PR refactors out killing of av recording and mosquitto_sub processes to a new function that is called in both `mission_cleanup` and `session_cleanup`, since Cmd+Q in macOS does not register as a regular signal like SIGINT / SIGTERM, so we need to kill the processes outside the trap.
=> Fix for handling Minecraft quitting using Cmd+Q on macOS.

tools/install_dependencies, tools/run_session
This PR implements a fix for the issue of `mosquitto` not properly starting up for Homebrew users when the `run_session` script is executed.
=> Implementing fix for Homebrew + mosquitto problem

tools/elkless_replayer
This PR adds a script to replay messages from a file created from an Elasticsearch dump of messages collected during an ASIST TA3 experimental trial. The script relies on the `mosquitto_pub` client executable, and does not require the ELK stack.
=> TA3 message file replayer

tools/elkless_replayer
This PR implements a fix for a few corner cases where the elkless_replayer script did not sort the messages correctly by time. The issue was that the timestamps were being treated as strings, and the string comparison function did not work perfectly for comparing timestamps in this representation.
This update uses the `python-dateutil` package to parse the ISO-8601 timestamps properly and enable correct comparison. Thanks to @pmdoll for discovering this issue.
=> Fix for corner cases in elkless_replayer

tools/elkless_replayer
Using python native client yields an order of magnitude in performance. Helps when we have 40k + messages.
Also includes minor updates to defend against bad json lines, missing keys and sort messages by header timestamp.
=> Use python native client

tools/install
As @pmdoll pointed out in #193 , the `tools/install` script implicitly assumed that the environment variable `CI` would be equal to 1. This PR fixes that issue.
=> Bugfix for tools/install

libs/mcg/CMakeLists.txt, tools/install_dependencies
This PR adds CMake install targets for `mcg` so it can be installed as a system-wide library if desired.
=> Adding install targets for mcg

tools/configuration_helpers, tools/install_dependencies, tools/install_from_source/macports
This PR updates the installation scripts to be compatible with macOS Big Sur, and also fixes a user-facing message that is emitted when MacPorts is present on a system and Homebrew is not.
=> Big sur update

tools/mumble_helper, tools/setup_murmur
This PR updates the mumble_helper script to make the version more easily changeable, and updated the Mumble version in the script from 1.3.2 to 1.3.3.
The `setup_murmur` script has also been updated to make the version and download URL more easily exposed for configuration.
=> Update Mumble helper script

tools/elkless_replayer
Adds functionality to the ELKless replayer tool to optionally create an
output file containing all the messages published to the bus during the
replay, with their topic added as a key (i.e., the .metadata file format
sans the `@timestamp` key).
This should make it easier to create output .metadata files that can be
replayed again using the ELKless replayer, compared to running a separate `mosquitto_sub` process to
collect the messages.
To create an output messages file, use the `-o` or `--output` option.
See example usage below.
./elkless_replayer <input_file> -o <output_file>
Also includes miscellaneous refactoring of the script to clean it up a
bit.
Collection
----------
- There is a new
Collector class that handles the message collection and manages its own
thread. The collector shuts …
=> Updates to elkless_replayer

human_experiments/scripts/check_disk_space, human_experiments/scripts/run_experiment
This PR checks whether we have at least 500GB of available space in `/data/cat` before proceeding with an experiment. If it gives an error message and exits the experiment in case it does not have enough space. 
close #386
=> Check space

human_experiments/scripts/inventory_script/inventory_script.py, human_experiments/scripts/inventory_script/utils/__init__.py, human_experiments/scripts/inventory_script/utils/inventory_script_logger.py, human_experiments/scripts/inventory_script/utils/run_baseline_tasks_data_validation.py, human_experiments/scripts/inventory_script/utils/run_minecraft_metadata_validation.py, human_experiments/scripts/inventory_script/utils/run_pupil_capture_validation.py, human_experiments/scripts/inventory_script/utils/run_xdf_check.py
**Minor updates:**
1. Hardcoding paths to folders like Minecraft, baseline_task, etc to avoid unnecessary os.walk(), hence saving search time. 
2. Hardcoding pupil capture file names and check if those files exist or not. 
3. Condition to handle multiple multiple trials under same trial ID for Minecraft metadata and report it as a warning. 
**Major updates:**
1. Using logging package to log info about the missing data to specific folder '<user defined path>/sanity_check/exp_*'
4. Added a wrapper script that loops across all files, passes it through the inventory script and logs info about missing data if any.
=> final commit

human_experiments/datasette_interface/label_data.py, human_experiments/datasette_interface/process_eeg_raw_data.py, human_experiments/datasette_interface/process_fnirs_raw_data.py, human_experiments/datasette_interface/process_raw_signals.py
This PR fixes a problem with fnirs that was reading from the wrong channels in the xdf stream and it multiplies eeg signals with 1e-6 to convert them from microvolts to volts.
=> Fix fnirs and eeg on database

human_experiments/datasette_interface/docker-compose.prod.yml, human_experiments/datasette_interface/metadata.yml
This PR changes the name of the inspect file in `docker-compose.prod.yml` to `inspect_file.json`, and specifies label columns in `metadata.yml` for better displaying of foreign key relationships in the Datasette interface.
=> Updates to docker-compose.prod.yml and metadata.yml
